name: Update Charts

on:
  schedule:
    # Runs daily at 6:15 p.m. PDT → 01:15 UTC
    - cron: "15 1 * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert pandas numpy geopandas xlrd requests matplotlib openpyxl seaborn

      # 4️⃣ Ensure folders exist (adjust if your notebook writes elsewhere)
      - name: Create folders
        run: |
          mkdir -p data
          mkdir -p docs/charts

      # 5️⃣ Run notebook safely
      - name: Run notebook
        run: |
          python -m nbconvert \
            --to notebook \
            --execute read_results.ipynb \
            --output read_results.ipynb \
            --ExecutePreprocessor.allow_errors=True

      # 6️⃣ Commit updated files
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/ read_results.ipynb
          git commit -m "Auto-update charts [skip ci]" || echo "No changes to commit"
          git push

      - name: Insert last updated date
        run: |
          DATE=$(date +"%B %d, %Y %I:%M %p PDT")
          for file in docs/*/index.html; do
            sed -i "s|DATE_PLACEHOLDER|$DATE|g" "$file"
          done
        
        